FROM oven/bun:latest AS build

WORKDIR /app

COPY package*.json bun.lockb /app/

RUN bun install

COPY . .

RUN bun run build

FROM oven/bun:latest

WORKDIR /app

COPY --from=builder /app /app

EXPOSE 80

CMD ["bun", "run", "start"]