FROM node:22-alpine AS build

WORKDIR /app

COPY package*.json ./

RUN bun install

COPY . .

RUN bun run build

FROM nginx:latest-alpine

COPY --from=build /app/dist /usr/share/nginx/html

COPY defaukt.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]