services:
  backend:
    # image: 127.0.0.1:5000/spintalk_backend:latest
    build: ./backend
    restart: unless-stopped
    ports:
        - "8000:8000"
    #expose:
      #- "8000"
    depends_on:
      - mongo
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.st_backend.rule=Host(`backend.localhost`)"
        - "traefik.http.routers.st_backend.entrypoints=https"
        - "traefik.http.routers.st_backend.tls=true"
        - "traefik.http.services.st_backend.loadbalancer.server.port=8000"
    environment:
        - MONGODB_URL=mongodb://admin:password@mongo:27017/ddf_db?authSource=admin
        - MAIL_USERNAME=spintalk@qdotnet.de
        - MAIL_PASSWORD=35,},ROstoR
        - MAIL_SERVER=mail.skycentral.de
        - MAIL_PORT=587
        - MAIL_STARTTLS=true
        - MAIL_SSL_TLS=false
        - MAIL_FROM=spintalk@qdotnet.de
        - SECRET_KEY=secret_key
    networks:
      - spintalk

  mongo:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - spintalk_database:/data/db
    environment:
        - MONGO_INITDB_ROOT_USERNAME=admin
        - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
        - spintalk

  frontend:
    image: 127.0.0.1:5000/spintalk_frontend:latest
    build: ./frontend
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      # - spintalk_overlay
      - spintalk

volumes:
  spintalk_database:
    #external: true

networks:
    #spintalk_overlay:
        #driver: overlay
    spintalk:
        driver: bridge