services:
  backend:
    build: ./backend
    restart: unless-stopped
    expose:
      - "8000"
    depends_on:
      - mongo
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.st_backend.rule=Host(`backend.localhost`)"
        - "traefik.http.routers.st_backend.entrypoints=https"
        - "traefik.http.routers.st_backend.tls=true"
        - "traefik.http.services.st_backend.loadbalancer.server.port=8000"
    environment:
        - MONGODB_URL=mongodb://admin:password@mongo:27017/ddf_db?authSource=admin
        - SECRET_KEY=secret_key#
    networks:
      - spintalk

  mongo:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
        - MONGO_INITDB_ROOT_USERNAME=admin
        - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
        - spintalk

  frontend:
    build: ./frontend
    restart: unless-stopped
    depends_on:
      - backend
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.st_frontend.rule=Host(`frontend.localhost`)"
        - "traefik.http.routers.st_frontend.entrypoints=https"
        - "traefik.http.routers.st_frontend.tls=true"
        - "traefik.http.services.st_frontend.loadbalancer.server.port=80"
    networks:
      - spintalk

volumes:
  mongo_data:

networks:
    spintalk:
        driver: overlay