name: Deploy to Test Server

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Setup SSH for server
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan 45.138.48.208 >> ~/.ssh/known_hosts

      - name: Setup SSH for GitHub
        run: |
          echo "${{ secrets.GH_DEPLOY_KEY }}" > ~/.ssh/actions_ssh
          chmod 600 ~/.ssh/actions_ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Deploy to Test Server
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa root@45.138.48.208 << 'EOF'
            set -e
            mkdir -p ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            if [ ! -d "/home/spintalk/.git" ]; then
              echo "Cleaning up the directory..."
              rm -rf /home/spintalk
              echo "Cloning the repository..."
              git clone git@github.com:qDotNet-Web/SpinTalk.git /home/spintalk
            fi
            cd /home/spintalk &&
            git stash &&
            git remote set-url origin git@github.com:qDotNet-Web/SpinTalk.git &&
            git config --global core.sshCommand "ssh -i ~/.ssh/actions_ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" &&
            git config pull.rebase false &&
            git pull origin dev &&
            docker stack deploy -c docker-compose.yml spintalk_stack
          EOF
